### ISSUE TITLE
python is case sensitive(closed)

### ISSUE THREAD

**Issue by camelStyleUser** [NavyDevy/Pyeditor#1]
you need to ```from tkinter import *``` not ```from Tkinter import *```.Tkinter is not a valid library name.tkinter however is.

**Comment by NavyDevy** [comment]
ok tell me every open source license

**Comment by camelStyleUser** [comment]
google it.im not a walking wikipedia.

**Comment by camelStyleUser** [comment]
try using GPL v3 license

**Comment by camelStyleUser** [comment]
do almost anything but mention the author

**Comment by camelStyleUser** [comment]
and use GPL v3 license when you fork the code
